# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate likelihood of (beta_hat_1[j], beta_hat_2[j])) given
#' rho, b, sigma_1j, sigma_2j, s_1j, s_2j where
#' alpha_kj ~ N(0, sigma_kj)
#'@export
loglik_ij <- function(rho, g, gp, q, sigma1, sigma2, b1, b2, s1, s2) {
    .Call('_cause_loglik_ij', PACKAGE = 'cause', rho, g, gp, q, sigma1, sigma2, b1, b2, s1, s2)
}

#' @title Calculate likelihood matrix -- version 7
#' @return A matrix that is p by K where p is the number of SNPs
#' and K is the grid size
#'@export
loglik_mat <- function(rho, g, gp, q, tsigma1, tsigma2, tbeta_hat_1, tbeta_hat_2, tseb1, tseb2) {
    .Call('_cause_loglik_mat', PACKAGE = 'cause', rho, g, gp, q, tsigma1, tsigma2, tbeta_hat_1, tbeta_hat_2, tseb1, tseb2)
}

#' @title Calculate likelihood -- version 7
#'@export
loglik <- function(rho, g, gp, q, tsigma1, tsigma2, tpi, tbeta_hat_1, tbeta_hat_2, tseb1, tseb2) {
    .Call('_cause_loglik', PACKAGE = 'cause', rho, g, gp, q, tsigma1, tsigma2, tpi, tbeta_hat_1, tbeta_hat_2, tseb1, tseb2)
}

#' @title Calculate likelihood matrix for LOO (SNPs by posterior samples)
#' @return A matrix that is p by L where p is the number of SNPs
#' and L is the number of posterior samples
#'@export
loglik_loo <- function(tg, tgp, tq, rho, tsigma1, tsigma2, tpi, tbeta_hat_1, tbeta_hat_2, tseb1, tseb2) {
    .Call('_cause_loglik_loo', PACKAGE = 'cause', tg, tgp, tq, rho, tsigma1, tsigma2, tpi, tbeta_hat_1, tbeta_hat_2, tseb1, tseb2)
}

#'@export
loglik_ij_Z1 <- function(rho, g, gp, q, sigma1, sigma2, b1, b2, s1, s2) {
    .Call('_cause_loglik_ij_Z1', PACKAGE = 'cause', rho, g, gp, q, sigma1, sigma2, b1, b2, s1, s2)
}

#'@export
loglik_ij_Z0 <- function(rho, g, gp, q, sigma1, sigma2, b1, b2, s1, s2) {
    .Call('_cause_loglik_ij_Z0', PACKAGE = 'cause', rho, g, gp, q, sigma1, sigma2, b1, b2, s1, s2)
}

#' @title Calculate likelihood matrix for LOO (SNPs by posterior samples)
#' @return A matrix that is p by L where p is the number of SNPs
#' and L is the number of posterior samples
#'@export
loglik_samps_Z1 <- function(tg, tgp, tq, rho, tsigma1, tsigma2, tpi, tbeta_hat_1, tbeta_hat_2, tseb1, tseb2) {
    .Call('_cause_loglik_samps_Z1', PACKAGE = 'cause', tg, tgp, tq, rho, tsigma1, tsigma2, tpi, tbeta_hat_1, tbeta_hat_2, tseb1, tseb2)
}

#' @title Calculate likelihood matrix for LOO (SNPs by posterior samples)
#' @return A matrix that is p by L where p is the number of SNPs
#' and L is the number of posterior samples
#'@export
loglik_samps_Z0 <- function(tg, tgp, tq, rho, tsigma1, tsigma2, tpi, tbeta_hat_1, tbeta_hat_2, tseb1, tseb2) {
    .Call('_cause_loglik_samps_Z0', PACKAGE = 'cause', tg, tgp, tq, rho, tsigma1, tsigma2, tpi, tbeta_hat_1, tbeta_hat_2, tseb1, tseb2)
}

